language: node_js

node_js:
- 'node'

sudo: required
dist: trusty

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
- sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian trusty main' >> /etc/apt/sources.list.d/mono-official.list"
- sudo apt-get update
- sudo apt-get install mono-devel
- export CC="gcc-4.8"
- export CXX="g++-4.8"
- export LINK="gcc-4.8"
- export LINKXX="g++-4.8"

script: npm run build

after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info


before_deploy: touch docs/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: docs
  on:
    branch: master
